-- Update medical_history table
ALTER TABLE medical_history
DROP COLUMN IF EXISTS medical_conditions,
DROP COLUMN IF EXISTS allergies,
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS date_of_birth DATE,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS has_diseases BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS diseases JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS disease_start_dates JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS takes_medications BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS medications JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS medication_start_dates JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS had_surgeries BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS surgeries JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS surgery_dates JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;